apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtyi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtyi
  template:
    metadata:
      labels:
        app: rtyi
    spec:
      containers:
      - image: okteto.dev/rtyi:latest
        name: rtyi
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "6ff101ec-1539-48bc-b921-473d721d800e"
        - name: Vless_Path
          value: "/vl234"
        - name: Vmess_UUID
          value: "6ff101ec-1539-48bc-b921-473d721d800e"
        - name: Vmess_Path
          value: "/vm333"
        - name: Share_Path
          value: "/v2link"
